//! Сборчный скрипт окна VOICEog.
//!
//! Единственная задача — вшить в `.exe` под Windows иконку и метаданные
//! (`VERSIONINFO`), чтобы Проводник и панель задач показывали нашу иконку, а
//! в «Свойствах» файла были версия/продукт/описание.
//!
//! Почему `embed-resource`, а не `winres`/`winresource`:
//!   * `winres` — заброшен (последний релиз годы назад);
//!   * `winresource` — живой форк `winres`, но для кросс-сборки MSVC с Linux
//!     ему нужен настоящий `rc.exe`, которого под `cargo-xwin` нет;
//!   * `embed-resource` умеет ровно наш случай: для `*-pc-windows-msvc` сам
//!     зовёт `llvm-rc` (есть в пакете `llvm`), для `*-pc-windows-gnu` —
//!     `x86_64-w64-mingw32-windres`, а на нативном Windows находит `rc.exe` в
//!     Windows SDK. Переключение — переменные `RC`/`RC_$TARGET`. Его же под
//!     капотом использует `tauri-winres`.
//!
//! Компилятор ресурсов по платформам:
//!   * нативный Windows (CI `windows-latest`, MSVC) — `rc.exe` из SDK;
//!   * Linux → `x86_64-pc-windows-msvc` (`cargo xwin`) — `llvm-rc`;
//!   * Linux → `*-pc-windows-gnu` — `x86_64-w64-mingw32-windres`.
//!
//! Поведение мягкое (грациозная деградация): если компилятора ресурсов нет,
//! `embed-resource` вернёт `NotAttempted`, мы напечатаем `cargo:warning=` и
//! сборка ПРОЙДЁТ — просто без иконки. Для не-Windows таргета — полный no-op,
//! Linux-сборка не затрагивается.

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    println!("cargo:rerun-if-changed=build.rs");

    // Linux (и любой не-Windows) не трогаем вообще: Windows-ресурсы тут не нужны.
    if env::var("CARGO_CFG_TARGET_OS").as_deref() != Ok("windows") {
        return;
    }

    // Менялась иконка — надо пересобрать.
    println!("cargo:rerun-if-changed=packaging/windows/app.ico");

    // embed-resource умеет брать компилятор ресурсов из RC/RC_$TARGET —
    // пусть смена этих переменных тоже перезапускает build.rs.
    println!("cargo:rerun-if-env-changed=RC");
    if let Ok(target) = env::var("TARGET") {
        println!("cargo:rerun-if-env-changed=RC_{target}");
        println!("cargo:rerun-if-env-changed=RC_{}", target.replace('-', "_"));
    }

    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let icon = manifest_dir.join("packaging/windows/app.ico");
    if !icon.is_file() {
        println!(
            "cargo:warning=VOICEog: иконка {} не найдена — пропускаю вшивание",
            icon.display()
        );
        return;
    }

    // --- .rc-скрипт собираем на лету в OUT_DIR ---
    let version = env::var("CARGO_PKG_VERSION").unwrap_or_else(|_| "0.0.0".into());
    let name = env::var("CARGO_PKG_NAME").unwrap_or_else(|_| "voiceog-window".into());
    let (v_major, v_minor, v_patch) = parse_version(&version);

    // В .rc путь идёт через C-подобный препроцессинг, поэтому бэкслэши Windows
    // путей экранируем. На Linux путь со слэшами "/" — экранировать нечего.
    let icon_rc = icon.to_string_lossy().replace('\\', "\\\\");

    // .rc обязан быть чистым ASCII: на нативном Windows-пути embed-resource
    // (windows_msvc.rs) НЕ выставляет code page 65001, в отличие от llvm-rc на
    // Linux. UTF-8 кириллица там превратилась бы в кракозябры в «Свойствах».
    // Поэтому FileDescription — латиница, а CARGO_PKG_DESCRIPTION (там русский)
    // в .rc не тянем. Все остальные строки уже ASCII.

    // RC использует BEGIN/END (не фигурные скобки), так что format! тут чистый.
    let rc_body = format!(
        "// Generated by build.rs - do not edit by hand.\n\
         1 ICON \"{icon}\"\n\
         \n\
         1 VERSIONINFO\n\
         FILEVERSION {vmaj},{vmin},{vpat},0\n\
         PRODUCTVERSION {vmaj},{vmin},{vpat},0\n\
         FILEFLAGSMASK 0x3fL\n\
         FILEFLAGS 0x0L\n\
         FILEOS 0x40004L\n\
         FILETYPE 0x1L\n\
         FILESUBTYPE 0x0L\n\
         BEGIN\n\
         \x20   BLOCK \"StringFileInfo\"\n\
         \x20   BEGIN\n\
         \x20       BLOCK \"040904b0\"\n\
         \x20       BEGIN\n\
         \x20           VALUE \"CompanyName\", \"VOICEog\"\n\
         \x20           VALUE \"FileDescription\", \"{desc}\"\n\
         \x20           VALUE \"FileVersion\", \"{version}\"\n\
         \x20           VALUE \"InternalName\", \"{name}\"\n\
         \x20           VALUE \"OriginalFilename\", \"{name}.exe\"\n\
         \x20           VALUE \"ProductName\", \"VOICEog\"\n\
         \x20           VALUE \"ProductVersion\", \"{version}\"\n\
         \x20       END\n\
         \x20   END\n\
         \x20   BLOCK \"VarFileInfo\"\n\
         \x20   BEGIN\n\
         \x20       VALUE \"Translation\", 0x409, 0x04b0\n\
         \x20   END\n\
         END\n",
        icon = icon_rc,
        vmaj = v_major,
        vmin = v_minor,
        vpat = v_patch,
        desc = "VOICEog local voice input",
        version = version,
        name = name,
    );

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let rc_path = out_dir.join("voiceog-window.rc");
    if let Err(e) = fs::write(&rc_path, rc_body) {
        println!("cargo:warning=VOICEog: не удалось записать {}: {e}", rc_path.display());
        return;
    }

    // --- собственно вшивание; при отсутствии компилятора не падаем ---
    match embed_resource::compile(&rc_path, embed_resource::NONE) {
        embed_resource::CompilationResult::Ok => {}
        embed_resource::CompilationResult::NotWindows => {}
        other => {
            println!("cargo:warning=VOICEog: ресурс не вшит ({other}) — сборка продолжится без иконки");
            println!("cargo:warning=VOICEog: для кросс-сборки поставь llvm (llvm-rc) или задай RC_x86_64_pc_windows_msvc");
        }
    }
}

/// "0.1.3", "0.1.3-beta.1", "1.2" → (major, minor, patch).
fn parse_version(v: &str) -> (u64, u64, u64) {
    let core = v.split(['-', '+']).next().unwrap_or("0");
    let mut it = core.split('.').map(|p| p.parse::<u64>().unwrap_or(0));
    (
        it.next().unwrap_or(0),
        it.next().unwrap_or(0),
        it.next().unwrap_or(0),
    )
}
